# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 961a0a5e73cff69e3a87d2e3e0a93f1f93039be785f1255c2f42efb3c4fa413837dc9e98cc75d085286ad25716688d706b2e1ebf43b22e38e2aae6cdc2a47e93

test:
  secret_key_base: 94d92e8c4d676446aa1fc17730da343c13936f36f57e1adb0015a762a874cfbf83c2664a864bf15cc717bc17ab965a27066cae4ecfc26434d3124610db9a07bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
